[phases.setup]
nixPkgs = ["chromium", "nss", "freetype", "fontconfig", "libX11", "libXext", "libXrender"]
nixLibs = ["chromium", "nss", "freetype", "fontconfig", "libX11", "libXext", "libXrender"]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install"]

[start]
cmd = "npx prisma migrate deploy && npm start"
